### ISSUE TITLE
Tag a version

### ISSUE THREAD

**Issue by davidanthoff** [JuliaIO/GZip.jl#57]
Please tag a version. The latest tagged version shows many deprecation warnings on julia 0.5. Master seems fine. With 0.5 RC0 out, we should get tagged versions to load without deprecation warnings.

**Comment by randyzwitch** [comment]
+1, if there are no other pending changes it would be great to have a new version. I'm trying to update my packages, and it would be great to remove one more source of noise.

**Comment by SimonDanisch** [comment]
Is this ready to tag or is there still work that needs to be done?
e.g. merging #41 ?!

**Comment by davidanthoff** [comment]
The latest tagged version also doesn't pass tests on Windows. My vote would be to tag now, and then fix #41 later. As far as I can tell there is no decrease in quality from that, but it would fix the deprecation warnings and make the whole julia 0.5 transition smoother.

**Comment by rsrock** [comment]
Looks like this is held up (just for a moment) due to an issue with the tag in LibExpat.

**Comment by PallHaraldsson** [comment]
@rsrock Just curious, what is the "issue with the tag in LibExpat"? [G]Zip has nothing to do with XML, and LibExpat neither REQUIREs GZip?!

**Comment by SimonDanisch** [comment]
Sorry, my bad for putting them together...I'll go fix the tag!

**Comment by rsrock** [comment]
No, they're not linked at all, it's just that Simon submitted both of them to METADATA together, and the PR was held up.

Thanks Simon!
