### ISSUE TITLE
Error loading zlib library

### ISSUE THREAD

**Issue by lselzer** [JuliaIO/GZip.jl#7]
Hello, I'm a experienced R user but I'm new to julia. I'm using Windows 8 64-bit and julia-2b22323495. Trying to load GZip gives the following error:

julia> import GZip
ERROR: error compiling anonymous: could not load module zlib1: no error
 in include_from_node1 at loading.jl:91 (repeats 2 times)
 in reload_path at loading.jl:114
 in require at loading.jl:48
at C:\Users\Luciano\AppData\Roaming\julia\packages\GZip\src\zlib_h.jl:8
at C:\Users\Luciano\AppData\Roaming\julia\packages\GZip\src\GZip.jl:74

I have downloaded the library and extracted in gzip\scr. Should it be somewhere else?

I must say that repeating import GZip a second time gives no error whatsoever.

Thanks

**Comment by vlandau** [comment]
I know this is an ancient issue, but hopefully someone sees this. I have a test pipeline in Travis on windows and the libz1 dependency is missing. I need to download zlib1.dll via the command line, so I was wondering if anyone knows the full path of the julia/lib folder?

Thanks!!
