### ISSUE TITLE
zlib1 problem on windows server in Travis CI

### ISSUE THREAD

**Issue by vlandau** [JuliaIO/GZip.jl#83]
Hi there,

I've been getting GZip errors related to zlib1 in a Julia 1.3 windows server Travis pipeline for a Julia package I'm developing. It's important to note that I do not have this problem in Julia 1.2 in the same Travis environment.

On the first try, I got the following error: (full output with stacktrace [here](https://travis-ci.org/Circuitscape/Omniscape.jl/jobs/612073548))
```julia
ERROR: LoadError: LoadError: error compiling top-level scope: could not load library "zlib1"
The specified module could not be found.
```

I saw from [this post](https://github.com/JuliaIO/GZip.jl/issues/7#issuecomment-21271313) that a potential solution is to download zlib1.dll and place it in the julia/lib folder. I tried that and had no success, so I tried placed the .dll in julia/bin instead. That caused a slightly different error: (full output with stacktrace [here](https://travis-ci.org/Circuitscape/Omniscape.jl/jobs/612143179))
```julia
ERROR: LoadError: LoadError: error compiling top-level scope: could not load library "zlib1"
%1 is not a valid Win32 application.
```
I've tried quite a few things but have had no luck. I'm not sure what to try next, so any help would be greatly greatly appreciated.

Thanks!

**Comment by giordano** [comment]
What do you need zlib for? If you have a binary dependency like this you should have a look at at https://github.com/JuliaPackaging/BinaryProvider.jl, I can provide you with the script to install zlib

As far as I can see your package doesn't require this one, so it's not clear to me why you opened this issue here.

**Comment by vlandau** [comment]
Because this is in the stacktrace. GZip threw the error
```
in expression starting at C:\Users\travis\.julia\packages\GZip\LD2ly\src\zlib_h.jl:11
in expression starting at C:\Users\travis\.julia\packages\GZip\LD2ly\src\GZip.jl:73
caused by [exception 1]
could not load library "zlib1"
The specified module could not be found.
```

**Comment by vlandau** [comment]
https://github.com/Circuitscape/Circuitscape.jl/blob/master/Project.toml

**Comment by vlandau** [comment]
> I can provide you with the script to install zlib

That would be very much appreciated.

**Comment by giordano** [comment]
I see, I was looking at https://github.com/Circuitscape/Omniscape.jl/blob/master/Project.toml

> That would be very much appreciated.

Now that I see where the error come from I agree this should be fixed here, not in your package

**Comment by vlandau** [comment]
Please let me know if there's any more info I can provide!

**Comment by giordano** [comment]
Ok, so zlib comes with julia itself, but the name of the binary library for Windows has been renamed in Julia 1.3, that's why the error

**Comment by vlandau** [comment]
Ah ha! So hopefully an easy fix then?

**Comment by giordano** [comment]
Yes, the fix is relatively easy, I just can't do it now because I'm not at the computer

**Comment by vlandau** [comment]
Sounds good. I'm in no rush since Julia 1.3 isn't even officially released yet. I really appreciate your help!

**Comment by vlandau** [comment]
CC: @ranjanan just something to be aware of if you start testing Circuitscape in Julia 1.3 on Windows before this patch gets released.
