### ISSUE TITLE
support for `do` blocks in GZip `open` functions?

### ISSUE THREAD

**Issue by RTbecard** [JuliaIO/GZip.jl#88]
For Julia's  `Base.open`, you can call it from a `do` block which automatically closes the file at the end and makes your code a little neater.
```julia
open("outfile", "w") do io
    write(io, data)
end
```
This behaves the same as python's recommended way of reading files.
```python
with open('file', 'w') as f:
    f.write("content")
``` 
The [source code](https://docs.julialang.org/en/v1/manual/functions/#Do-Block-Syntax-for-Function-Arguments) for this is super simple.
```julia
function open(f::Function, args...)
    io = open(args...)
    try
        f(io)
    finally
        close(io)
    end
end
```

Is there any reason this functionality coulden't be implemented here?  Or perhaps theres design reasons against it?  If not, I'd be interested in making a pull request (so long as this is as easy as I think it looks).

**Comment by m-wells** [comment]
Doesn't this already work?

**Comment by RTbecard** [comment]
oh, yup, yes it is.  My bad :/  

I never tried it, as I didn't see anything in the [docs](https://gzipjl.readthedocs.io/en/latest/) referring to it or descriptions of the `open` methods which accepted a function as a first argument.
